In [1]:
import numpy as np

In [2]:
n1 = np.array([5,469,889,7,98,456,163,214,67,3,1,])

# Addition

In [3]:
n1 +52

array([ 57, 521, 941,  59, 150, 508, 215, 266, 119,  55,  53])

# Substaction

In [4]:
n1 -2

array([  3, 467, 887,   5,  96, 454, 161, 212,  65,   1,  -1])

# Division

In [5]:
n1 /2

array([  2.5, 234.5, 444.5,   3.5,  49. , 228. ,  81.5, 107. ,  33.5,
         1.5,   0.5])

# multiplecation

In [7]:
n1 * 2

array([  10,  938, 1778,   14,  196,  912,  326,  428,  134,    6,    2])