In [1]:
num = input('Eddnter the name: ')


Enter the name: Sugatmoon
Sugatmoon


In [2]:
print(55)

55


In [72]:
import numpy as np
n1 = np.array([2,1,5,4,9,7,898,7])
n1

array([  2,   1,   5,   4,   9,   7, 898,   7])

In [73]:
type(n1)

numpy.ndarray

In [77]:
n1.shape

(8,)

In [82]:
import numpy as np1
n2 = np1.array([[12,3,7,8,4,],[5,9]])
n2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [78]:
n1

array([  2,   1,   5,   4,   9,   7, 898,   7])

In [86]:
import numpy as np
n1 = np.array([[10,11,12,13,14,15],[1,2,3,4,5,6]])
n1

array([[10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6]])

In [87]:
n1.shape


(2, 6)

In [88]:
type(n1)

numpy.ndarray

In [114]:
n1[0:]

array([[10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6]])

In [124]:
n2 = np.zeros((6,6))
n2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
dd

In [127]:
n3 = np.full((12,35),2)
n3

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2

In [133]:
n4 = np.arange(10,1000,5)
n4

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200,
       205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265,
       270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330,
       335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385, 390, 395,
       400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450, 455, 460,
       465, 470, 475, 480, 485, 490, 495, 500, 505, 510, 515, 520, 525,
       530, 535, 540, 545, 550, 555, 560, 565, 570, 575, 580, 585, 590,
       595, 600, 605, 610, 615, 620, 625, 630, 635, 640, 645, 650, 655,
       660, 665, 670, 675, 680, 685, 690, 695, 700, 705, 710, 715, 720,
       725, 730, 735, 740, 745, 750, 755, 760, 765, 770, 775, 780, 785,
       790, 795, 800, 805, 810, 815, 820, 825, 830, 835, 840, 845, 850,
       855, 860, 865, 870, 875, 880, 885, 890, 895, 900, 905, 91

In [ ]:
dd

In [171]:
n5 = np.random.randint(10,1000,500)
n5

array([641,  40, 113, 180, 848, 387, 930, 157, 679, 633, 359, 331, 376,
       298, 102, 608, 503, 976, 433,  85, 950, 257, 135, 894, 726, 911,
       894, 521, 709,  85, 733, 267, 619, 774, 879, 421, 700, 131, 236,
       485,  53, 372, 607, 719,  16, 687, 639, 858, 824, 373, 667, 369,
       860, 188, 295, 492, 806, 809, 787,  13, 606,  89, 760, 309, 843,
       214, 304, 350, 250, 355, 155, 588, 738, 113, 579, 475,  37, 792,
       768, 948, 491, 802, 475, 198, 620, 806, 620, 308, 925, 483, 666,
       374, 468, 498, 565, 941, 418, 326, 415,  32, 431, 418, 167, 612,
       863,  54, 272, 853, 231, 287, 819,  62, 107, 644, 326, 978, 512,
       977, 997, 601, 985, 130, 628, 840, 221, 647, 340, 781, 117, 981,
       964, 689, 174, 762, 454, 204, 372, 288, 376, 128, 151, 417, 478,
       194,  74, 914, 942, 920,  98, 694, 798, 583, 838, 900, 239, 933,
       672, 775, 688, 812, 347, 121, 487, 166, 429, 416, 540, 396, 630,
       576,  70, 300, 965, 148, 476, 358, 646, 477, 378, 900,  1

In [173]:
n1

array([[10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6]])

In [175]:
n1.shape

(2, 6)

In [178]:
n1.shape =(6,2)
n1

array([[10, 11],
       [12, 13],
       [14, 15],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6]])

In [180]:
n1

array([[10, 11],
       [12, 13],
       [14, 15],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6]])

In [181]:
type(n1)

numpy.ndarray