# Creating Single dimensional array

In [14]:
import numpy as np

n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

# Creating Multi-Dimensional Array

In [15]:
import numpy as np

n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [16]:
type(n2)

numpy.ndarray

# Extracting elements

In [17]:
n1

array([10, 20, 30, 40])

In [18]:
n1[0]

10

In [19]:
n1[1:3]

In [ ]:
n2

In [ ]:
n2[0,0]

In [ ]:
n2[0]

array([10, 20, 30, 40])

In [ ]:
n2[1,3]

10

# np.zeros

In [24]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [25]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# np.arange

In [26]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
import numpy as np
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

# np.full

In [28]:
import numpy as np
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [29]:
#np.randit

In [30]:
import numpy as np
n1=np.random.randint(1,100,5)
n1

array([48, 68, 54, 54, 49])

In [31]:
n1.shape

(5,)

In [32]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

#NumPy Shape

In [33]:
n1.shape = (3,2)
n1.shape

(3, 2)

# Numpy Sum

In [34]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2])

100

In [35]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [36]:
np.sum([n1,n2],axis=1)

array([30, 70])

# NumPy comparison

In [37]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.equal(n1,n2)

array([ True, False, False])

In [38]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.array_equal(n1,n2)

False

# Joining Arrays

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.vstack((n1,n2))

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n1=n1/2
n1

In [ ]:
n1=n1+1
n1

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [ ]:
np.intersect1d(n1,n2)

In [ ]:
np.setdiff1d(n1,n2)

# numpy math functions

In [ ]:
import numpy as np
n1=np.array([1,5,3,100,4,48])
np.std(n1)

# Save & Load

In [ ]:
import numpy as np

In [ ]:
n1 = np.array([1,23,5,4,6,45,5,8,8,964,4])

In [ ]:
np.save('This is final array file',n1)

In [ ]:
n2 = np.load('This is final array file.npy')

In [ ]:
n2

# BroadCasting array
- All the input arrays have the same shape.
- Arrays have the same number of dimensions, and the length of each dimension is either a common length or 1.
- Array with the fewer dimension can be appended with '1' in its shape.

In [47]:
import numpy as np

In [48]:
n1 = np.array([1,2,3])
n1.shape

(3,)

In [49]:
n2 = np.array([4,5,6])
n2.shape = (3,1)
n2

array([[4],
       [5],
       [6]])

#### now we broadcasting n1 and n2

In [50]:
n1 + n2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

# Accessing Coloum, Row, Element (individual)

#### @For Coloum

In [55]:
    n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
    n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
n1[:,1]

array([2, 5, 8])

#### @For Row

In [60]:
n1[2]

array([7, 8, 9])

#### @Accessing Element

In [63]:
n1[2,2]

9

# Transpose of Matrix

In [65]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# dot Multiplication

In [69]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
n2 = np.array([[3,6,4],[7,6,3],[9,6,7]])
n2

array([[3, 6, 4],
       [7, 6, 3],
       [9, 6, 7]])

In [76]:
n1.dot(n2)

array([[ 44,  36,  31],
       [101,  90,  73],
       [158, 144, 115]])

In [77]:
n2.dot(n1)

array([[ 55,  68,  81],
       [ 52,  68,  84],
       [ 82, 104, 126]])