In [6]:
import numpy as np

In [7]:
n1 = np.array([1,2,3,4,5,6,7,8,9])

In [8]:
n2 = np.array([9,8,7,6,5,4,3,2,1])

# Vertical stack

In [10]:
np.vstack((n1,n2))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

# Horizontal stack

In [12]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Column stack

In [14]:
np.column_stack((n1,n2))

array([[1, 9],
       [2, 8],
       [3, 7],
       [4, 6],
       [5, 5],
       [6, 4],
       [7, 3],
       [8, 2],
       [9, 1]])